### ISSUE TITLE
Repo organization suggestions

### ISSUE THREAD

**Issue by disa-mhembere** [neurodata/ProgLearn#102]
A few things to consider:
- Generating html API docs via sphinx
- Complete install section in `README`
- Add specific versions for all packages to Dependencies and requirements.txt
- Be more specific about hardware requirements e.g. at least 4GB of RAM, 64bit OS etc
- is `.egg-info` necessary?
- populate tutorials and examples
- try to organize the repo packages to only put user facing code in the top-level dir and move code for experiments etc elsewhere

**Comment by levinwil** [comment]
Closing since all steps have been done, other than the last which is Issue #309
