### ISSUE TITLE
Kernel Density Forests

### ISSUE THREAD

**Issue by levinwil** [neurodata/ProgLearn#118]
Overall Idea: To smooth posteriors, train a kernel density estimate on the means of each class within each leaf node.

Goals:
1. Compare this to the calibration of empirical posteriors, ideally to have more smooth and calibrated posteriors from UF
2. Use this KDE to get posteriors within leaf nodes of L2F transformers. These KDEs will be voters that (ideally) have more smooth and calibrated posteriors, therefore (hopefully) increasing FTE/BTE.

**Comment by jovo** [comment]
I don't really understand your goals, they do not seem to be SMART.

goals:

1. write down the math of what we are trying to do
2. write down pseudocode for how you'd do it
3. implement it, 
4. demonstrate that it works using 1 tree and like 4 samples
5. reproduce fig 1 from UF, but adding Kernel Density Forests

**Comment by levinwil** [comment]
For those interested in following this issue, I am working Kernel Density Graphs (the general form of Kernel Density Forests, which also includes Kernel Density Networks) in the following repository: https://github.com/levinwil/KernelDensityGraphs

**Comment by levinwil** [comment]
Closing because this project is being honest at [https://github.com/levinwil/ActivationGraphBinning](https://github.com/levinwil/ActivationGraphBinning)
