### ISSUE TITLE
Add max_depth as a parameter to LifelongClassificationForest and UncertaintyForest

### ISSUE THREAD

**Issue by levinwil** [neurodata/ProgLearn#247]
Simply follow the usage of default_finite_sample_correction/finite_sample_correction in both classes to include max_depth, with the minor change that max_depth is a transformer kwarg, as opposed to a voter kwarg. IT IS VERY IMPORTANT TO DISTINGUISH BETWEEN DEFAULT_MAX_DEPTH AND MAX_DEPTH: default_max_depth (like default_finite_sample_correction) is the parameter fed to the internal PL as a default if none is provided to max_depth in 'add_task', while max_depth (like finite_sample_correction) is used in add_task to override the default, if provided.

**LLFC**
1. Update [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L43) to allow LLCF to accept 'default_max_depth' (with a default of 30)
2. Add a new line after [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L46) to internally save default_max_depth under self.default_max_depth
3. Update [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L49) to include "max_depth" : default_max_depth as a transformer_kwarg
5. Update [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L59) to include max_depth (with a default of 30) as a parameter to add_task. 
6. Update [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L84) to first check if max_depth is None and, if so, assigned max_depth = self.default_max_depth
7. Add a new line after [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L90) and [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L114) to input transformer_kwargs = {"max_depth" : max_depth} 

**UF**
1. Update [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L114) to allow max_depth (with a default of 30) as a parameter to init
2. Add a new line after [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L174) to internally save max_depth to self.max_depth
3. Add a new line after [this line](https://github.com/neurodata/progressive-learning/blob/main/proglearn/forest.py#L189) to feed default_max_depth = max_depth to LLFC

In general, just follow the steps of default_finite_sample_correction/finite_sample_correction.

Please make sure you update ALL docstrings this affects.

Please make sure you unit test this stuff to make sure things are fed to functions appropriately, and make sure your implementation passes those unit tests locally via PyTest.

**Comment by srahul1222** [comment]
@levinwil I'd like to work on this issue

**Comment by levinwil** [comment]
Closing per PR #283
