### ISSUE TITLE
Simplify each benchmark tutorial (Jupyter notebook)

### ISSUE THREAD

**Issue by PSSF23** [neurodata/ProgLearn#286]
**Is your feature request related to a problem? Please describe.**
Extension of #41 and a Sprint 1 issue suggested by @levinwil 

**Describe the solution you'd like**
Simplified tutorials for all benchmarks

**Additional context (e.g. screenshots)**
Currently finished tutorials:
label_shuffle #259 
random_class #271 
xor_nxor #284

**Comment by levinwil** [comment]
Closing, since all baseline tutorials have been implemented on the staging branch (other than recruitment, which is in Issue #56 )
