### ISSUE TITLE
Refine the xor_xnor experiment tutorial

### ISSUE THREAD

**Issue by bstraus1** [neurodata/ProgLearn#301]
Specifically, I will:

- [x] Update the notebook using [Jayanta's notebook](https://github.com/neurodata/ProgLearn/blob/staging/benchmarks/parity_experiment/experiment.ipynb)
- [x] Ensure that there are no warnings/unwanted outputs in the notebook (currently there are some)
- [x] Go line by line with the code, explaining each step
- [x] Move long functions to a separate .py file to improve readability
- [x] Restrict sample sizes in the final figure to X>750
- [x] Remove progress print statements throughout the code
- [x] Find and replace all "FTE" with "BTE", and vice versa in the last figure

**Comment by levinwil** [comment]
@bstraus1 How is this different than https://github.com/neurodata/ProgLearn/blob/docs/docs/tutorials/xor_nxor_exp.ipynb?

**Comment by bstraus1** [comment]
Those three points I've written above. 
In my opinion, the current experiment has too large blocks of code. I'll move long functions to a separate file and go line-by-line in the tutorial.

**Comment by levinwil** [comment]
Ok. Can you also please fix the following problem: 
<img width="661" alt="Screen Shot 2020-10-12 at 1 04 13 PM" src="https://user-images.githubusercontent.com/20121139/95780258-912b5d80-0c99-11eb-98d2-5ac8b2a7254e.png">
The region circled in black should not exist. If we don't have any data from N-XOR, we can't compute anything with respect to N-XOR.

**Comment by bstraus1** [comment]
Ah, so just restrict the x axis to sample sizes >750?

**Comment by levinwil** [comment]
Yup!

**Comment by levinwil** [comment]
@bstraus1 Could you also please get rid of all the progress print statements?

**Comment by bstraus1** [comment]
Yep!

**Comment by levinwil** [comment]
Can you also switch the labels for FTE and BTE?

**Comment by levinwil** [comment]
@bstraus1 Can you please update the original checklist at the top of this issue to include the changes mentioned in the comments?

**Comment by bstraus1** [comment]
This issue can now be closed @levinwil. Sorry that I can't do this myself.
