### ISSUE TITLE
Simplify rotation_cifar tutorial and move functions to a separate file

### ISSUE THREAD

**Issue by srahul1222** [neurodata/ProgLearn#305]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Tutorial should be simplified so that only the necessary code is in the notebook, while the rest of the functions should be moved to a separate file.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by levinwil** [comment]
Closing, per PR #319
