### ISSUE TITLE
Run UF figure 1 tutorial with real parameters

### ISSUE THREAD

**Issue by bstraus1** [neurodata/ProgLearn#321]
Goal: see if the results with the real parameters are comparable to the UF paper.

**Comment by levinwil** [comment]
@bstraus1 this seems to be related to #62 

Is that correct? If so, could you please close this issue and make a comment with your tasking on #62

**Comment by bstraus1** [comment]
I'm unclear on what #62 is exactly. Can you elaborate?

**Comment by levinwil** [comment]
My impression is that it means to reproduce all the UF notebooks (including UF fig 1) using ProgL functions. It seems as if that is what your goal is here. Would you say that is the case?

**Comment by bstraus1** [comment]
Not the case here. Currently the fig1 notebook already uses ProgL functions. This issue is for running it with the real parameters rather than the test parameters using a machine with more computational power.

**Comment by levinwil** [comment]
Which notebook is the fig1 notebook?

I know your issue is to use the real parameters rather than the tutorial parameters. That means that, once you use the real parameters, your goal is to reproduce the results of the UF paper fig 1 but with ProgLearn functions, as the title of #62 suggests.

**Comment by bstraus1** [comment]
The notebook using ProgL functions is already written [here](https://github.com/neurodata/ProgLearn/blob/main/docs/tutorials/uncertaintyforest_fig1.ipynb). It just needs to be run on some more powerful machine.

**Comment by levinwil** [comment]
So that is the tutorial notebook. Please correct me if I am wrong but I believe you are simply rerunning this notebook but with the parameters that match those used to generate the UF paper fig 1. In that case, you are literally reproducing a UF paper fig result, but with ProgLearn function. That is exactly the tasking for issue #62

**Comment by bstraus1** [comment]
#62 has no description and the title isn't well-worded. If it means to rerun tutorials that already use ProgL functions on real parameters, then yes #321 falls under #62. Otherwise, it does not.

**Comment by levinwil** [comment]
1. By “real parameters” do you mean those used to generate figures? If so, please call them “paper parameters” or something along those lines - that is much more clear. Similarly, I believe that by “test parameters” you mean parameters used to generate tutorials. If so, please call them “tutorial parameters” for similar reasons. 
2. #62 does not mean to rerun tutorials using paper parameters, as it was created before we had any tutorials. I believe it means to recreate the UF notebooks used to generate the UF paper figures, but substituting ProgLearn functions in those notebooks. Hence, my suggestion that you comment your tasking on that issue and close this one.

**Comment by bstraus1** [comment]
I can do that, but wouldn’t it be better practice to link these issues since this is one I can fully complete while the other is a much larger umbrella issue?

**Comment by levinwil** [comment]
I personally think it would be best to mark this issue as a duplicate, mention that you are closing it because it falls under #62, and then comment a checklist of tasks you'd like to complete related to this issue that fall under the umbrella of #62 

Just my opinion. Ideally, we'd have everything related to #62 on the thread under #62

**Comment by bstraus1** [comment]
That makes sense. I'll do that now.
