### ISSUE TITLE
`max_depth` overload

### ISSUE THREAD

**Issue by hhelm10** [neurodata/ProgLearn#322]
`max_depth = None` for add_task is a bit confusing -- typically, `max_depth = None` implies "grow tree until pure" but here it uses means to use `self.default_max_depth`

**Comment by levinwil** [comment]
@hhelm10  Do you have a suggested fix? I would say an alternative default value for the parameter ‘max_depth’ to add_task, but I’m not sure what that would be. We could do something silly like making the default ‘max_depth = “default”’ but that seems really hacky.

**Comment by hhelm10** [comment]
yes, a simple suggestion -- change from `max_depth` to `max_depth_for_task` so as to eliminate the name conflict with sklearn

**Comment by levinwil** [comment]
Well still run into the same problem even if we do that renaming. That hyperparam, regardless of name, controls the max_depth eventually fed to sklearn.

**Comment by hhelm10** [comment]
right -- the issue is that we are using the same name as sklearn but not `None` in the same way --

this is problematic, for example, when you set the default max_depth to be 30 but for a particular task you want to force leaf purity

**Comment by levinwil** [comment]
Yup. Exactly as I was saying in my first comment. This is an undesirable. I think the only solution that I see is to change the default value of the max_depth parameter in add_task to something besides none (e.g. max_depth = “default” - or just something that couldn’t possibly be a value fed to sklearn as a max_depth parameter) just so we can know when to use default_max_depth or a non-default value in add_task

**Comment by levinwil** [comment]
Closing per PR #324
