### ISSUE TITLE
Add n_estimators as a parameter to add_task in forest.py.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#326]
**Is your feature request related to a problem? Please describe.**
We need this feature to run experiments with fixed resources with cifar and parity data.

**Describe the solution you'd like**
Just add one more argument as n_estimators.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by levinwil** [comment]
Closing per PR #327
