### ISSUE TITLE
Create xor-rxor tutorial notebook using Jayanta's code

### ISSUE THREAD

**Issue by bstraus1** [neurodata/ProgLearn#330]
I plan to:

- [x] Create a notebook similar to [Emily's for xor-nxor](https://github.com/neurodata/ProgLearn/blob/main/docs/tutorials/xor_nxor_exp.ipynb)

- [x] Use code from [Jayanta's notebook](https://github.com/neurodata/ProgLearn/blob/staging/benchmarks/parity_experiment/experiment.ipynb)

**Comment by levinwil** [comment]
@bstraus1 Is this the same task as #301 ? If not, how do they differ?

**Comment by bstraus1** [comment]
@levinwil This is not the same as the title implies. I just met with Jayanta and he said that I may want to break up the notebook into two notebooks: XOR-NXOR & XOR-RXOR. That being said, these issues are very linked and I feel that both should exist simultaneously (but not in the same issue).

**Comment by levinwil** [comment]
@bstraus1 That makes sense. Before moving on to the new XOR-RXOR, could you please clean up the existing XOR-NXOR notebook?

**Comment by bstraus1** [comment]
@levinwil Reading my mind 😉
