### ISSUE TITLE
Change tutorials to match new BTE/FTE definitions

### ISSUE THREAD

**Issue by levinwil** [neurodata/ProgLearn#345]
Both the code and the notebook text

**Comment by PSSF23** [comment]
Adding source of new definitions might be helpful.

**Comment by levinwil** [comment]
<img width="417" alt="Screen Shot 2020-10-28 at 8 20 56 PM" src="https://user-images.githubusercontent.com/20121139/97510456-26497a00-195b-11eb-9f4c-485f4da9a027.png">
<img width="432" alt="Screen Shot 2020-10-28 at 8 21 01 PM" src="https://user-images.githubusercontent.com/20121139/97510459-26e21080-195b-11eb-9642-5543f08f7e32.png">

Here are the new definition. The short change is to use the ratio of the averages, rather than the average of the ratios.

**Comment by PSSF23** [comment]
Should benchmarks be updated as well?

**Comment by levinwil** [comment]
Yup

**Comment by PSSF23** [comment]
Should we close this issue? @levinwil

**Comment by levinwil** [comment]
Yup yup. Good catch @PSSF23
