### ISSUE TITLE
Optimize tutorial notebooks for online display

### ISSUE THREAD

**Issue by PSSF23** [neurodata/ProgLearn#356]
My issue is about making sure all tutorials are displayed correctly on netlify-produced [website](https://proglearn.neurodata.io/index.html). Even if the tutorial notebooks are displayed correctly on GitHub or local host, they might show nonsense equations and uninformative titles online.

Some guidelines:
 - Use [`label_shuffle_exp`](https://github.com/neurodata/ProgLearn/blob/staging/docs/tutorials/label_shuffle_exp.ipynb) tutorial as an example. Everything displays correctly on its [website](https://proglearn.neurodata.io/tutorials/label_shuffle_exp.html).
 - Format the first markdown line with "#" at front and make it the **one and only** informative title instead of "overview" or other terms.
 - Format the subtitles with "##" at front so that they will show up as submenus on website.
 - Check the netlify preview for your PR, which is included as one of the required checks.

#### Snapshot of documentation error:

![Screen Shot 2020-11-05 at 13 04 36](https://user-images.githubusercontent.com/20309845/98280460-4a571d80-1f50-11eb-81b6-03a205500661.png)

**Comment by PSSF23** [comment]
If employing the website now with `staging` branch, we will have at least 3 tutorial pages named "Tutorial Overview." Do you mind reformat them in a more informative way? @bstraus1

**Comment by bstraus1** [comment]
Can you elaborate on what you’d like me to do exactly about the redundant titles?

**Comment by PSSF23** [comment]
@bstraus1 Use the "#"format once and only on the true title I suppose? Like:

# Installation Guide

**Comment by levinwil** [comment]
@PSSF23 What is the status of this issue? Is there anything else to update? I haven't been following very closely.

**Comment by PSSF23** [comment]
@levinwil Current tutorials should be addressed, but I want to keep it open as a reference. New notebooks keep coming~

**Comment by levinwil** [comment]
@PSSF23 We could just make a wiki page. I think that would be more appropriate as a guide. Or we could add this to the contribution guidelines. I think issues should be concrete tasks that can be closed once finished - but it doesn't seem like this has a concrete end-point.

**Comment by PSSF23** [comment]
@levinwil adding to contribution guideline is a good idea. I will start working on it and close the issue when the guideline is updated.

**Comment by levinwil** [comment]
@PSSF23 Sounds good :)
