### ISSUE TITLE
Find smaller p/p* parameters that satisfy the sample_size_experiment.ipynb tutorial

### ISSUE THREAD

**Issue by Michael-Ainsworth** [neurodata/ProgLearn#367]
In sample_size_experiment.ipynb, data is generating from the sparse parity distribution using parameters `p` and `p*`. The goal of this issue is to:
- Explore the effect of smaller `p` and `p*` parameters on the experiment outcome
- Identify smaller parameters that can demonstrate the same relationship

If improved experiment parameters are found, they can be included in sample_size_experiment.ipynb as an addendum

**Comment by levinwil** [comment]
@Michael-Ainsworth Has this been mostly finished?

**Comment by levinwil** [comment]
Closing Per PR #384
