### ISSUE TITLE
Describe figure significance in UncertaintyForest tutorials

### ISSUE THREAD

**Issue by jovo** [neurodata/ProgLearn#372]
http://proglearn.neurodata.io/tutorials/uncertaintyforest_fig1.html
http://proglearn.neurodata.io/tutorials/uncertaintyforest_fig2.html

please rename, fig1 and fig2 do not mean anything to our users, please be more descriptive.

**Comment by PSSF23** [comment]
Specific requirement for #37

**Comment by EYezerets** [comment]
@jovo @PSSF23 how about
1. uncertaintyforest_posteriorestimates
2. uncertaintyforest_conditionalentropyestimates
3. uncertaintyforest_mutualinformationestimates
?
