### ISSUE TITLE
Fix for decider data splitting

### ISSUE THREAD

**Issue by latasianguy** [neurodata/ProgLearn#385]
My issue is about fixing the decider data splitting in `progressive_learner.py` within the `set_decider` function.
Previously, the decider has access to all data, even if we had given it an allotted amount of data. The change fixes it so that it uses its allotted amount set by `decider_idx = self.task_id_to_decider_idx[task_id]`

Changes:
```
    self.task_id_to_decider[task_id].fit(
        X, y, transformer_id_to_transformers, transformer_id_to_voters
    )
```

```
    decider_idx = self.task_id_to_decider_idx[task_id]
    self.task_id_to_decider[task_id].fit(
        X[decider_idx], y[decider_idx], transformer_id_to_transformers, transformer_id_to_voters
    )
```

**Comment by levinwil** [comment]
Closing Per PR #386
