### ISSUE TITLE
Migrate travis test to new domain

### ISSUE THREAD

**Issue by PSSF23** [neurodata/ProgLearn#391]
My issue is about moving the travis test to new domain (`travis.com`). The old domain (`travis.org`) will become unavailable at the end of this year, and current tests on it encountered delays due to limited worker availability.

Official page for information: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

#### Additional context
This issue applies to all repositories using `travis.org`.

**Comment by PSSF23** [comment]
@sampan501 do you mind helping us with this migration, as you have already done so for `hyppo` I believe? Thanks a lot!

**Comment by sampan501** [comment]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#the-migration-steps

**Comment by PSSF23** [comment]
@sampan501 @jdey4 apparently the migration is only open to @neurodata members.

**Comment by sampan501** [comment]
Oh I can update it

**Comment by PSSF23** [comment]
@sampan501 please! Thank you!

**Comment by sampan501** [comment]
@jdey4 or @levinwil might have to do it. I don't see ProgLearn as an option in my migrate tab

**Comment by PSSF23** [comment]
@sampan501 it would be under the neurodata organization's migrate tab.

**Comment by sampan501** [comment]
Yea I understand that but I think only an admin has the ability to migrate. I'm not currently an admin of Proglearn

**Comment by PSSF23** [comment]
@sampan501 Thanks for the help! Let's see if @jdey4 and @levinwil have the permission needed.

**Comment by levinwil** [comment]
I do not have the correct permissions to perform this. I cannot get access to `neurodata/Proglearn` from Travis. Maybe does @jdey4 have access?

**Comment by PSSF23** [comment]
Don't know what happened on `travis` side, but `travis.org` was certainly not "_officially closed down completely no later than December 31st, 2020_." The migration is thus postponed until further updates.

**Comment by PSSF23** [comment]
Apparently `travis` does not fulfill our needs anymore, thus closing.
