### ISSUE TITLE
Make Jupyter notebook showing the capability of progressive-learning on different datasets

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#40]

**Comment by jovo** [comment]
@jdey4 let's give them other example datasets.  maybe MNIST would be easy and illustrative? 
and permuted MNIST?
or some other MNIST variants?

**Comment by jdey4** [comment]
The MNIST dataset mentioned in this paper could be used: https://arxiv.org/abs/1904.07734

**Comment by latasianguy** [comment]
Can I be added to this issue?

**Comment by jdey4** [comment]
I thought Kaleab was doing it for his sprint 0.

**Comment by latasianguy** [comment]
Ok, I didn't see a link back to this

**Comment by levinwil** [comment]
Is there a distinction between this and Issue #48? They seem to be the same or similar issues - are they similar enough to close one or the other?

**Comment by srahul1222** [comment]
I'm interested in applying the ProgLearn algorithms to the [Food-101](https://www.kaggle.com/kmader/food41) dataset from this [paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Kornblith_Do_Better_ImageNet_Models_Transfer_Better_CVPR_2019_paper.pdf)
