### ISSUE TITLE
Key Error prevents running uncertaintyforest_posteriorestimates tutorial

### ISSUE THREAD

**Issue by EYezerets** [neurodata/ProgLearn#408]
I encountered a Key Error that did not exist when the [uncertaintyforest_posteriorestimates.ipynb](https://github.com/neurodata/ProgLearn/blob/staging/docs/tutorials/uncertaintyforest_posteriorestimates.ipynb) tutorial and corresponding functions in [unc_forest_tutorials_functions.py](https://github.com/neurodata/ProgLearn/blob/staging/docs/tutorials/functions/unc_forest_tutorials_functions.py) were first merged into the [staging](https://github.com/neurodata/ProgLearn/tree/staging) branch, but arose in the last few weeks when I attempted to run the notebook again in my own fork. 

This afternoon I cloned the neurodata/Proglearn repository as-is to see if the error exists there in the staging branch, and it does. When one sets `parallel = False` [in the 3rd code block](https://github.com/neurodata/ProgLearn/blob/a39b0a02ed2f63a33c63796dc2be4ea899c08d4e/docs/tutorials/uncertaintyforest_posteriorestimates.ipynb#L131) of the notebook, the notebook stops running at the [4th block](https://github.com/neurodata/ProgLearn/blob/a39b0a02ed2f63a33c63796dc2be4ea899c08d4e/docs/tutorials/uncertaintyforest_posteriorestimates.ipynb#L150) and throws the error shown below.

It references the [estimate_posterior](https://github.com/neurodata/ProgLearn/blob/a39b0a02ed2f63a33c63796dc2be4ea899c08d4e/docs/tutorials/functions/unc_forest_tutorials_functions.py#L43) function in unc_forest_tutorials_functions.py, but I have not made changes to that function in the staging branch since the notebook was merged more than a month ago, if I remember correctly.

(This error appears to be independent of the `kwargs` error in `proglearn/forest.py` that @PSSF23 kindly fixed.)

I think the error may lie in other recent changes to the `proglearn` package, but I am not sure. 

I would very much appreciate your help, as I was also working on adding a ground truth line to the figure produced by this notebook, and this Key Error stopped the plotting from one day in mid-December to the next.

#### Reproducing code example:

```

# This is the code that actually generates data and predictions.
for algo in algos:
    algo['predicted_posterior'] = estimate_posterior(algo, n, mean, var, num_trials, X_eval, parallel = parallel)
```

#### Error message

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-ae35aac15077> in <module>
      1 # This is the code that actually generates data and predictions.
      2 for algo in algos:
----> 3     algo['predicted_posterior'] = estimate_posterior(algo, n, mean, var, num_trials, X_eval, parallel = parallel)

~/NDDebug/ProgLearn/docs/tutorials/functions/unc_forest_tutorials_functions.py in estimate_posterior(algo, n, mean, var, num_trials, X_eval, parallel)
     71         predicted_posterior = np.zeros((num_trials, X_eval.shape[0]))
     72         for t in tqdm(range(num_trials)):
---> 73             predicted_posterior[t, :] = worker(t)
     74 
     75     return predicted_posterior

~/NDDebug/ProgLearn/docs/tutorials/functions/unc_forest_tutorials_functions.py in worker(t)
     63     def worker(t):
     64         X, y = generate_data(n, mean, var) # generating data with the function above
---> 65         obj.fit(X, y) # using the fit function of the learner to fit the data
     66         return obj.predict_proba(X_eval)[:,1] # using the predict_proba function on the range of desired X
     67 

~/uf/lib/python3.8/site-packages/proglearn-0.0.3-py3.8.egg/proglearn/forest.py in fit(self, X, y)
    343         """
    344         X, y = check_X_y(X, y)
--> 345         return self.lf_.add_task(X, y, task_id=0)
    346 
    347     def predict_proba(self, X):

~/uf/lib/python3.8/site-packages/proglearn-0.0.3-py3.8.egg/proglearn/forest.py in add_task(self, X, y, task_id, n_estimators, tree_construction_proportion, kappa, max_depth, feature_combinations, density)
    172 
    173         X, y = check_X_y(X, y)
--> 174         return self.pl_.add_task(
    175             X,
    176             y,

~/uf/lib/python3.8/site-packages/proglearn-0.0.3-py3.8.egg/proglearn/progressive_learner.py in add_task(self, X, y, task_id, transformer_voter_decider_split, num_transformers, transformer_class, transformer_kwargs, voter_class, voter_kwargs, decider_class, decider_kwargs, backward_task_ids, forward_transformer_ids)
    649         # from new transformer to previous tasks
    650         if num_transformers > 0:
--> 651             self.add_transformer(
    652                 X,
    653                 y,

~/uf/lib/python3.8/site-packages/proglearn-0.0.3-py3.8.egg/proglearn/progressive_learner.py in add_transformer(self, X, y, transformer_data_proportion, transformer_voter_data_idx, transformer_id, num_transformers, transformer_class, transformer_kwargs, backward_task_ids)
    530         # train voters and deciders from new transformer to previous tasks
    531         for existing_task_id in np.intersect1d(backward_task_ids, self.get_task_ids()):
--> 532             self.set_voter(transformer_id=transformer_id, task_id=existing_task_id)
    533             self.set_decider(
    534                 task_id=existing_task_id,

~/uf/lib/python3.8/site-packages/proglearn-0.0.3-py3.8.egg/proglearn/progressive_learner.py in set_voter(self, transformer_id, task_id, voter_class, voter_kwargs, bag_id)
    355         for transformer_num, transformer in enumerate(transformers):
    356             if transformer_id == task_id:
--> 357                 voter_data_idx = self.task_id_to_bag_id_to_voter_data_idx[task_id][
    358                     transformer_num
    359                 ]

KeyError: 200
```

#### Version information

- OS: Ubuntu for Windows (notebook run in VSCode)
- Python Version 3.8.2
- Package Version 0.0.3

**Comment by PSSF23** [comment]
@EYezerets I think I figured out part of the problem.

So for a start, line 187 of `progressive_learner.py` has this internal function of appending `transformer` to its corresponding `transformer_id`:

https://github.com/neurodata/ProgLearn/blob/effa495fa6adef3ffda7d48f5419cfe956751fc1/proglearn/progressive_learner.py#L187-L191

And then on line 658, in the `add_task` function, the `task_id` is assigned to be the `transformer_id`:

https://github.com/neurodata/ProgLearn/blob/effa495fa6adef3ffda7d48f5419cfe956751fc1/proglearn/progressive_learner.py#L650-L663

As **all** `task_id` entries of the `UncertaintyForest` class are 0, **all** the `transformer` data are recorded in the same `dict` and double its size each round. Other `dict` objects, however, are not aware of this doubling and maintain their respective capacity, thus resulting in the key out of boundary:

https://github.com/neurodata/ProgLearn/blob/effa495fa6adef3ffda7d48f5419cfe956751fc1/proglearn/progressive_learner.py#L355-L359

For solution, I suppose changing the appending method to handle `transformer` data replacement might be a viable way.
