### ISSUE TITLE
Consider standardizing notebook formats

### ISSUE THREAD

**Issue by v715** [neurodata/ProgLearn#413]
[`nb-black`](https://github.com/dnanhkhoa/nb_black) is a jupyter extension that auto-formats notebook cells using Black.

Might be worthwhile adding to all tutorial notebooks for consistency -- a simple fix that would enhance readability.

#### Snapshot of documentation error:

We don't allow code formatting like this in our code, so why in our tutorials?
![Screen Shot 2021-01-12 at 9 54 59 PM](https://user-images.githubusercontent.com/29757116/104400683-d40f0280-5520-11eb-9670-28af0c98131c.png)

**Comment by PSSF23** [comment]
@v715 While I agree with you on having good formats for jupyter notebooks, the `nb_black` extension is one that I have concerns about its implementations. You can check out [this issue](https://github.com/dnanhkhoa/nb_black/issues/29) I made a while ago, which explains how `nb_black` mess up the notebook source codes.

**Comment by v715** [comment]
That's interesting, didn't know that's how nb_black works under the hood...

**Comment by PSSF23** [comment]
@v715 I just found this other tool called `jupyter-black`: https://github.com/drillan/jupyter-black, which seems to work more elegantly. Yet one problem of formatting jupyter notebooks is that we can not check it with tests. Feel free to optimize our [tutorial guidelines](https://github.com/neurodata/ProgLearn/blob/staging/docs/contributing.rst#tutorial-guidelines)!

**Comment by kfenggg** [comment]
Can I be assigned to this?
