### ISSUE TITLE
Further exploration of progressive learning capabilities between different datasets

### ISSUE THREAD

**Issue by emilyachang** [neurodata/ProgLearn#422]
**Is your feature request related to a problem? Please describe.**
This is an extension of the work done previously in #397 (and, somewhat, #40 and #48) to all the datasets within the following github repo: https://github.com/neurodata/LLF_tidy_images

**Describe the solution you'd like**
The plan is to run the FTE/BTE experiment between the different datasets to see if transfer can be achieved between other datasets beyond MNIST/fashion-MNIST.

**Additional context**
Will be working with @chenyugoal and @srahul1222 to look at other applications of progressive learning.

**Comment by srahul1222** [comment]
@PSSF23 I would like to be assigned to this issue as well

**Comment by chenyugoal** [comment]
@PSSF23 Please assign me as well! Thanks!
