### ISSUE TITLE
Sub-issue of #423 (Match Proglearn Documentation to Verde): Add Sphinx Gallery

### ISSUE THREAD

**Issue by bstraus1** [neurodata/ProgLearn#425]
See #423 

This is a sub-task with the specific goal to implement a Sphinx Gallery in the proglearn documentation similar to that in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation.

**Comment by bstraus1** [comment]
May I be assigned to this issue @sampan501?

**Comment by rflperry** [comment]
We also switched to sphinx gallery for mvlearn, modeled after sklearn, if you want a package to reference, https://mvlearn.github.io/

**Comment by bstraus1** [comment]
Oh! That's very helpful. Thanks!
