### ISSUE TITLE
Do the recruitment experiment on a larger dataset with many tasks.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#47]
Please go through the recruitment experiment code in the experiment folder and read the paper: https://arxiv.org/pdf/2004.12908.pdf

**Comment by jdey4** [comment]
Please go through this repo: https://github.com/neurodata/LLF_tidy_images

**Comment by jovo** [comment]
@jdey4 please link to jupyter notebook running the recruitment experiment.
if one does not yet exist, make a new issue for somebody to make that.

**Comment by jovo** [comment]
this is the paper demonstrating transfer learning capabilities on this datasets
https://openaccess.thecvf.com/content_CVPR_2019/papers/Kornblith_Do_Better_ImageNet_Models_Transfer_Better_CVPR_2019_paper.pdf

**Comment by mkusman1** [comment]
I would want to do this issue for sprint 1. Is it still not assigned?

**Comment by emilyachang** [comment]
@jdey4 could i be assigned to this issue as well, following #56?
