### ISSUE TITLE
Fix formatting errors throughout the docs.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#470]
My issue is about ...

#### Snapshot of documentation error:
<img width="1288" alt="Screen Shot 2021-08-19 at 9 19 24 PM" src="https://user-images.githubusercontent.com/52499217/130169121-bbfac82b-38e4-47f2-bd2c-9bd99099bf4f.png">

**Comment by PSSF23** [comment]
@jdey4 The current website is not the latest version. It's not built on `main` or `staging`.

**Comment by jdey4** [comment]
@PSSF23 are you sure? We should close this issue after merging the staging into main then.

**Comment by PSSF23** [comment]
@jdey4 Yes, the tutorial list is incomplete and your screenshot is from a previous version. I'm trying to locate the reason why the deploy changed. Do you have any clue?

**Comment by jdey4** [comment]
Maybe this has something to do with it: https://app.netlify.com/teams/amp/builds/

**Comment by PSSF23** [comment]
Sorry don't have permission to see the page.
