### ISSUE TITLE
Fix the Gaussian Xor and XNOR experiment and the plots.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#475]
My issue is about ...
The parity experiment uses the old name PLF and the Y-axis should be changed to log-scale in order to be consistent with the main draft.
#### Snapshot of documentation error:

<img width="717" alt="Screen Shot 2021-09-10 at 11 05 54 AM" src="https://user-images.githubusercontent.com/52499217/132883736-caf5d4b8-78b4-49d7-bb6a-fb0825a7ae91.png">

**Comment by PSSF23** [comment]
@jdey4 https://github.com/neurodata/ProgLearn/blob/staging/docs/experiments/functions/xor_nxor_functions.py
