### ISSUE TITLE
Choose a different dataset other than vision (image tasks) and run progressive-learning algorithms on that dataset.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#48]

**Comment by jovo** [comment]
please provide links to papers/datasets that they could use @jdey4

**Comment by jdey4** [comment]
Using transfer learning on this covid dataset may result in a good paper: https://github.com/ieee8023/covid-chestxray-dataset.

**Comment by jdey4** [comment]
More covid data:

1. https://towardsdatascience.com/covid-19-imaging-dataset-chest-xray-ct-for-annotation-collaboration-5f6e076f5f22
2. https://aimi.stanford.edu/resources/covid19

**Comment by jdey4** [comment]
We can also try the datasets in this repo: https://github.com/neurodata/LLF_tidy_images and mentioned in this paper: https://openaccess.thecvf.com/content_CVPR_2019/papers/Kornblith_Do_Better_ImageNet_Models_Transfer_Better_CVPR_2019_paper.pdf.

**Comment by Ayuking** [comment]
### My plan for this issue:

- [ ] week 3, learn how to visualize data elegantly in python.

- [ ] week 4-5, learn how to collect and handle big datasets.

- [ ] week 6-9, optimize parameters and submit pull request.

- [ ] week 10-final, review and merge.

### My questions:
- Does that sound feasible? (for a python beginner)
- Do I need to compare the performance of ProgL with other algorithms?

**Comment by srahul1222** [comment]
Seeing as how no one has been assigned to this issue yet, can I still take on this issue for my Sprint 1? 

If Chenyu is also interested in this, can we create two separate issues for this and try running the algorithms on two different datasets?

**Comment by sampan501** [comment]
sure that is fine. I think that is a reasonable amount of work and if you finish you can just run on another data set

**Comment by chenyugoal** [comment]
Glad you join! We can share information under this issue, when searching and collecting datasets. That will accelerate our work I think. @srahul1222

**Comment by chenyugoal** [comment]
Jayanta, the datasets you mentioned above are image tasks. Can I still use them in experiments? @jdey4
