### ISSUE TITLE
cannot import name 'Adam' from 'keras.optimizers' in UncertaintyForest tutorial

### ISSUE THREAD

**Issue by kfenggg** [neurodata/ProgLearn#482]
My issue is about below error when running the uncertainty forest tutorial (uncertaintyforest_running_example.ipynb)
<img width="1680" alt="proglearnissue" src="https://user-images.githubusercontent.com/89429238/133529019-6acba630-5d6f-44d0-a776-d77fc2b7fa3d.png">

#### Reproducing code example:

```
from proglearn.forest import UncertaintyForest
```

#### Error message

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-cf85b86fcaae> in <module>
----> 1 from proglearn.forest import UncertaintyForest
      2 from proglearn.sims import generate_gaussian_parity

~/opt/anaconda3/lib/python3.8/site-packages/proglearn/__init__.py in <module>
      1 from .forest import *
----> 2 from .network import *
      3 
      4 __version__ = "0.0.4"

~/opt/anaconda3/lib/python3.8/site-packages/proglearn/network.py in <module>
     10 from .deciders import SimpleArgmaxAverage
     11 
---> 12 from keras.optimizers import Adam
     13 from keras.callbacks import EarlyStopping
     14 

ImportError: cannot import name 'Adam' from 'keras.optimizers' (/Users/kevin/opt/anaconda3/lib/python3.8/site-packages/keras/optimizers.py)
```

#### Version information

- OS: macOS Monterey V12.0
- Python 3.8.8
- Package Version: downloaded from staging from 9/15/21, 9/12/21, and main from sometime last week

**Comment by PSSF23** [comment]
fixed in `staging`: https://github.com/neurodata/ProgLearn/blob/staging/proglearn/network.py
