### ISSUE TITLE
Write unit tests for the functions in the repo.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#49]

**Comment by latasianguy** [comment]
Would like to write unit tests for UF - David Shi

**Comment by ypeng22** [comment]
Hi, is there more than 1 peron's worth of work for this issue? If so, can I be added to this? - Yu-Chung Peng

**Comment by jdey4** [comment]
@ypeng22 and @latasianguy please mention here the specific function that you want to write unit tests for and make an issue providing a link to the code. You both can choose different functions in this way.

**Comment by ypeng22** [comment]
Ok, I will write unit tests for all functions of TreeRegressionTransformer in /progressive-learning/tests/test_treeregression.py Is that specific enough? @jdey4

**Comment by ypeng22** [comment]
https://github.com/neurodata/progressive-learning/issues/82
This is the issue I made, is this what you meant?

Also, I found out there are two test folders, one located at /progressive-learning/tests/
and the other located at /progressive-learning/proglearn/tests/
Is proglearn different from progressive-learning? The files in the two different directories seem to be testing files located in the same directory though.

**Comment by williamrxu** [comment]
Hi, I have also been looking at functions to write unit tests for. Are there specific functions that we want tested?

**Comment by jdey4** [comment]
@ypeng22 we want unit_tests in /progressive-learning/proglearn/tests/.

**Comment by jdey4** [comment]
@williamrxu claim a function or module and write unit_test for it.

**Comment by jovo** [comment]
@latasianguy claim a function, make a new issue, reference this one. it should be clear that you are *not* completing this issue, so it does not make sense.

**Comment by levinwil** [comment]
Closing, per Issue #13
