### ISSUE TITLE
Make a Jupyter notebook clearly showing the steps in the recruitment experiment.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#56]
This should be done before addressing #47 and the code to follow is: https://github.com/neurodata/progressive-learning/blob/master/experiments/recruitment_exp/experiment.py

**Comment by mkusman1** [comment]
@jdey4  recruitment_exp is not in the experiments folder

**Comment by jdey4** [comment]
Here it is: https://github.com/neurodata/progressive-learning/tree/paper_experiments/experiments/recruitment_exp

**Comment by emilyachang** [comment]
@jdey4 if no one else is currently working on this, could i be assigned to it?

**Comment by levinwil** [comment]
@emilyachang would you still like to be put on this issue?

**Comment by emilyachang** [comment]
@levinwil yes, if possible!

**Comment by levinwil** [comment]
@emilyachang just assigned you. If possible, please PR the notebook into the 'docs/tutorials/' folder on the staging branch. The final notebook should be slim, clean, minimal - it is a tutorial. You should be able to explain every word of code in the final notebook, why it's there, what it's doing, and why there isn't a better (or shorter/cleaner) alternative. Does that make sense?

**Comment by emilyachang** [comment]
@levinwil yep! apologies about the typos/lack of code cleanup in the previous notebook i worked on.

**Comment by levinwil** [comment]
@emilyachang no worries haha that wasn’t supposed to be a subtle @ to your previous notebook - I just give those same suggestions to everyone writing tutorials
