### ISSUE TITLE
re-write all the UF notebooks called ProgL repo functions

### ISSUE THREAD

**Issue by jovo** [neurodata/ProgLearn#62]

**Comment by bstraus1** [comment]
I have recently rewritten the UF figure 1 notebook using ProgL repo functions. 
It is complete with #95 and #189. 
However, as an additional step, I'm going to run the notebook using paper-parameters (as opposed to the tutorial-parameters, which run more quickly) with @EYezerets 's help. Currently this notebook is being finalized and will be PR'ed soon.

**Comment by levinwil** [comment]
@EYezerets Do you know which other figs should be completed to close this issue?
