### ISSUE TITLE
Show double-descent for random forest

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#66]
sample Xi from the unit square.
if Xi is better than the line going from (0,0) to (1,1), Yi=1, otherwise, Yi=0.
Now, train a decision tree on n samples from that, but restrict the size of the tree somehow, eg, setting max-level to 1, then 2, then 3, then…. all the way until each leaf node is pure.
But then, start adding more trees, with the same ‘no max level’ so they are pure.
Probably repeat the whole thing 1000 times
Now, plot average generalization error (error on held-out data) as a function of # of total leaf nodes.

**Comment by zCompKid** [comment]
Hey Jayanta, I would like to work on this.
