### ISSUE TITLE
test whether these things actually work on a windows machine

### ISSUE THREAD

**Issue by jovo** [neurodata/ProgLearn#69]

**Comment by PSSF23** [comment]
@jovo is #178 and `travis` test enough to close this issue?

**Comment by jovo** [comment]
dunno, that is a @jdey4 and @levinwil question

**Comment by levinwil** [comment]
@PSSF23 i personally think Travis is enough to close this issue, but I can’t provide much more info since I do not have a windows machine. We run tests on a windows machine - not sure if that is enough.

**Comment by PSSF23** [comment]
Close until further issues arise.
