### ISSUE TITLE
show that RF eventually wins

### ISSUE THREAD

**Issue by jovo** [neurodata/ProgLearn#83]
choose a joint distribution (X,Y) that has the following property

1. when sample size is low, RF. achieves better generalization error than a specific parametric DN
2. when sample size is medium, that specific parametric DN does better than RF
3. when sample size is large, RF again does better than DN

i'm not exactly sure which (X,Y) has this property, empirically, though I would suspect lots of things.  i might start with something simple like the distributions described in the SPORF paper, eg, parity.

**Comment by Michael-Ainsworth** [comment]
Could I hear a bit more about this issue? Would this be related to a specific paper? Thank you!

**Comment by Michael-Ainsworth** [comment]
In addition, could I be added to this issue?

**Comment by jovo** [comment]
https://www.biorxiv.org/content/10.1101/2020.04.29.068460v2

makes the point a little, we'll probably need simulation data for the streams to cross

**Comment by Michael-Ainsworth** [comment]
Current plan for issue:

- [ ] Create experiment classes which input RF parameters and DN parameters/model architecture
- [ ] Expand experiment classes to include intuitive visualizations to show the effect of sample size on each model
- [ ] Design separate tutorial notebook for testing distributions
- [ ] Identify distributions that best demonstrate hypothesis

Goal: Observe RF winning with large sample sizes. Merge experiment into neurodata/progressive-learning/tutorials

**Comment by Michael-Ainsworth** [comment]
![sparse_parity_p14_3_ss35000_DN_14_8_1_RF_100_trs_20_iters_8_bs](https://user-images.githubusercontent.com/59264468/96355454-c972d780-10af-11eb-8373-aa6234313494.png)
This is the experiment run on the sparse parity dataset with parameters p=14 and p*=3 for 20 iterations. Do these parameters do a good job of demonstrating the intended relationship? Or should I explore additional parameters to try and make the relationship more clear?

**Comment by jovo** [comment]
we need more data.
how many trees?
how many trials?
where are the errorbars?
how large is the deep net, etc.

also please link the jupyter notebook as well.

On Sat, Oct 17, 2020 at 7:51 PM Michael Ainsworth <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> [image: sparse_parity_p14_3_ss35000_DN_14_8_1_RF_100_trs_20_iters_8_bs]
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59264468%2F96355454-c972d780-10af-11eb-8373-aa6234313494.png&data=04%7C01%7Cjovo%40jhu.edu%7C4778c512d02a480775ba08d872f78b31%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637385754801879677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fe5tnFEC7FLh%2BvvR8KIH4I0nnFl%2BsGjzWH4%2FMn3a8s8%3D&reserved=0>
> This is the experiment run on the sparse parity dataset with parameters
> p=14 and p*=3 for 20 iterations. Do these parameters do a good job of
> demonstrating the intended relationship? Or should I explore additional
> parameters to try and make the relationship more clear?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fissues%2F83%23issuecomment-711094858&data=04%7C01%7Cjovo%40jhu.edu%7C4778c512d02a480775ba08d872f78b31%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637385754801879677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zDI6b4HtLHtnvMMjwhdd9FkcRsDgObR4U1tqzy1fnDY%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4VJEH4H7DVSV4C44E3SLIUXLANCNFSM4Q67DCQA&data=04%7C01%7Cjovo%40jhu.edu%7C4778c512d02a480775ba08d872f78b31%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637385754801889677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9ZPPFzt6jX3mly6tiMH0V8%2F2kRfsQa4RBuTd09oUnDc%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by Michael-Ainsworth** [comment]
![sparse_parity_p14_3_ss35000_DN_14_8_1_RF_100_trs_20_iters_8_bs_eb](https://user-images.githubusercontent.com/59264468/96377926-dbf41c00-1156-11eb-91c8-9e32bcc260ed.png)
RF uses 500 trees
DN has 1 hidden layer with 8 nodes (14 input nodes, 1 output node) run for 10 epochs

Data points are the average over 20 trials
Error bars were calculated using the standard error of the mean

I have attached my jupyter notebook below for reference:
https://nbviewer.jupyter.org/github/Michael-Ainsworth/progressive-learning/blob/rf-wins/docs/tutorials/test_distributions.ipynb

**Comment by jovo** [comment]
ok that is helpful.
do you have a timing plot?
the lines are not that smooth, so i'd want something more like 500 trials i
think, assuming that is computationally tractable?

On Sun, Oct 18, 2020 at 3:46 PM Michael Ainsworth <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> [image: sparse_parity_p14_3_ss35000_DN_14_8_1_RF_100_trs_20_iters_8_bs_eb]
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59264468%2F96377926-dbf41c00-1156-11eb-91c8-9e32bcc260ed.png&data=04%7C01%7Cjovo%40jhu.edu%7Ce7b96cb9e17e46e4c33708d8739e85d2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386471978711441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fy12U6cPVUIoXP%2Buon%2FH5W1Xfddi1yCMb%2FUkxAyPCWg%3D&reserved=0>
> RF uses 500 trees
> DN has 1 hidden layer with 8 nodes (14 input nodes, 1 output node) run for
> 10 epochs
>
> Data points are the average over 20 trials
> Error bars were calculated using the standard error of the mean
>
> I have attached my jupyter notebook below for reference:
>
> https://nbviewer.jupyter.org/github/Michael-Ainsworth/progressive-learning/blob/rf-wins/docs/tutorials/test_distributions.ipynb
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnbviewer.jupyter.org%2Fgithub%2FMichael-Ainsworth%2Fprogressive-learning%2Fblob%2Frf-wins%2Fdocs%2Ftutorials%2Ftest_distributions.ipynb&data=04%7C01%7Cjovo%40jhu.edu%7Ce7b96cb9e17e46e4c33708d8739e85d2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386471978711441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XgxGVdgJNZ5F3h%2FQuHPB2nNQrg4HTQqjZLJKzsbpByY%3D&reserved=0>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fissues%2F83%23issuecomment-711412261&data=04%7C01%7Cjovo%40jhu.edu%7Ce7b96cb9e17e46e4c33708d8739e85d2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386471978721441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X5Y8sTy7xc%2BQYSYezleihqSntmIR9Ps%2B5rZT%2BojC0YE%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4QJBJAGWG4HOXJA423SLNAZVANCNFSM4Q67DCQA&data=04%7C01%7Cjovo%40jhu.edu%7Ce7b96cb9e17e46e4c33708d8739e85d2%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386471978721441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QF97VTavDfG0YbUXu4vRhSLM12SBfckd1ukjbu7Y8cY%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by Michael-Ainsworth** [comment]
I do not currently have a timing plot, but I believe it took around 2 hours to run 20 trials. I will run the model overnight and comment the results with a timing plot. Thanks!

**Comment by jovo** [comment]
great

On Sun, Oct 18, 2020 at 11:50 PM Michael Ainsworth <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> I do not currently have a timing plot, but I believe it took around 2
> hours to run 20 trials. I will run the model overnight and comment the
> results with a timing plot. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fissues%2F83%23issuecomment-711496128&data=04%7C01%7Cjovo%40jhu.edu%7C24854a9bfe5b404ea96408d873e21f8d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386762319889431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bmv%2FJs4iG%2F4hXh8IZZUYlwQOK362L%2BBQhmG4%2FzJBDsY%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4X74YPWZXCZWWJ4UELSLOZQLANCNFSM4Q67DCQA&data=04%7C01%7Cjovo%40jhu.edu%7C24854a9bfe5b404ea96408d873e21f8d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637386762319899429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e4UmhXjsor17pKeZgTNYfcOgu7G9iaB%2FuPAPDgfApf8%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by Michael-Ainsworth** [comment]
![sparse_parity_p14_3_ss35000_DN_14_8_1_RF_100_trs_100_iters_8_bs_eb](https://user-images.githubusercontent.com/59264468/96511175-b3d6ec80-122c-11eb-8aea-55254c3f10e9.png)
![Time_plot_DN_14_3_500_trees_8_bs](https://user-images.githubusercontent.com/59264468/96511188-ba656400-122c-11eb-9305-b10bc23e149c.png)
I ran the model on 100 trials, and it appears the distinction between model accuracies becomes a bit less clear at high sample sizes. In addition, RF is still rather inconsistent. 

I plan on slightly decreasing the DN complexity to see if the DN will plateau at a higher classification error.

**Comment by Michael-Ainsworth** [comment]
![dnn_4hn_3bs_10iters_rf_overlay_FINAL_30000](https://user-images.githubusercontent.com/59264468/97206747-855a9380-178f-11eb-91f7-346510e9fc89.png)
Sparse parity distribution with parameters p=14 and p*=3

RF uses 500 trees
DN has 1 hidden layer with 4 hidden nodes and a batch size of 3

Data points are the average over 100 trials
Error bars are calculated using the standard error of the mean

A few other combinations of DN parameters gave similar results. Any feedback/critiques would be helpful.

**Comment by jovo** [comment]
its a thing of beauty.
write the caption.
it would be Figure 3B in this
https://www.biorxiv.org/content/10.1101/2020.04.29.068460v3
maybe also write a few sentences for the text to include,
and respond to this issue accordingly.



On Mon, Oct 26, 2020 at 1:41 PM Michael Ainsworth <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> [image: dnn_4hn_3bs_10iters_rf_overlay_FINAL_30000]
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59264468%2F97206747-855a9380-178f-11eb-91f7-346510e9fc89.png&data=04%7C01%7Cjovo%40jhu.edu%7C6b447e5e134348f8536f08d879d67d3e%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637393309420456344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k95YyG9wdkjYjizRdU%2B%2FnSb%2FhMWzMLFSGvniwI4XZkU%3D&reserved=0>
> Sparse parity distribution with parameters p=14 and p*=3
>
> RF uses 500 trees
> DN has 1 hidden layer with 4 hidden nodes and a batch size of 3
>
> Data points are the average over 100 trials
> Error bars are calculated using the standard error of the mean
>
> A few other combinations of DN parameters gave similar results. Any
> feedback/critiques would be helpful.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fissues%2F83%23issuecomment-716713792&data=04%7C01%7Cjovo%40jhu.edu%7C6b447e5e134348f8536f08d879d67d3e%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637393309420466343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hw1I97GJ7o4kCtrIrSYdw2ACY1yXxbWUtU73kt%2Bgi8k%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4WCZYPM5MZT4HC37KDSMWYGPANCNFSM4Q67DCQA&data=04%7C01%7Cjovo%40jhu.edu%7C6b447e5e134348f8536f08d879d67d3e%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637393309420466343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z%2B8x2Pm3RyA54rw%2F6bInt1i%2B8%2BB5zsWhE0GadHWcT7o%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
