### ISSUE TITLE
Add tutorial for uncertainty forests

### ISSUE THREAD

**Issue by bstraus1** [neurodata/ProgLearn#95]
Create a python notebook demonstrating how to download, run, and use the uncertainty forest class.

**Comment by bstraus1** [comment]
May I be assigned to this issue for sprint1?

**Comment by bstraus1** [comment]
Approach [plan](https://docs.google.com/document/d/1BVXmwJWIdK97N2HLWBOn3IDQ7o3WTrO1d14mew4c4eQ/edit) for the issue:

Make notebooks creating tutorials for the following:
- [ ] Installation: Write a python notebook explaining how to install the Progressive-learning repo on a local machine 
- [ ] Package Setup: Write a python notebook explaining how to (1) create a virtual environment (2) install requirements (3) run jupyter notebook 
- [ ] Data Setup: Write a python notebook explaining how to set up sample data that can be used to test the UncertaintyForest class
- [ ] Running: Write a python notebook demonstrating the methods of the UncertaintyForest class and how they are used 
- [ ] Analyzing: Write a python notebook demonstrating how to analyze the results of running the methods of the UncertaintyForest class

**Comment by levinwil** [comment]
@bstraus1 This is awesome! Thanks for going the extra mile with the planning 👍

**Comment by EYezerets** [comment]
@bstraus1 Looks good to me! Thanks!

**Comment by bstraus1** [comment]
Can I be assigned to this issue?

**Comment by levinwil** [comment]
Closing, per PR #295
